pgcon:
  gui:
    width: 960
    height: 540
  input:
    width: 1920
    height: 1080
    ppi: 237
    frameInterval: 5
    renderInterval: 5
    cacheSize: 100
  output:
    baudRate: 9600
    pressTime: 85
    captureTime: 5000